---
title: "alex_analysi"
author: "Tim Nieuwenhuis"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
library(scales)
dat <- read.csv("alex_g_stats_4_18.csv")



```

Add data columns

```{r cars}
#remove na data
dat <- dat %>% drop_na()

curr_year <- 2020

dat <- dat %>% mutate(difference = end - start, year_learned = 2020 - difference) %>% select(-placehold)

race = 2010
winner = 2011
Rules_Trick = 2012
DSU = 2014
beach_music = 2015
rocket = 2017
HoS = 2019
```

#plot
Plot one is a simply histogram and acumulative distribution histogram
```{r}
##Two histograms

melt_dat <- melt(dat %>% select(-difference, -year_learned))

#get mean
start_mean <- mean(dat$start)
start_median <- median(dat$start)

end_mean <- mean(dat$end)
end_median <- median(dat$end)

sum_dat <- NULL
sum_dat$mean <- c(end_mean, start_mean)
sum_dat$median <- c(end_median, start_median)
sum_dat$group <- factor(c("end", "start"), levels = c("start", "end"))
sum_dat <- as.data.frame(sum_dat)

# Interleaved histograms
ggplot(melt_dat, aes(x=value, fill=variable)) +
  geom_histogram(position="identity", alpha=0.5, color = "black" ,
                 #bins = (max(melt_dat$value) - min(melt_dat$value)
                  binwidth = 1)+
  
  scale_x_continuous(breaks=seq(min(melt_dat$value),max(melt_dat$value),2)) +   
  #geom_vline(data=sum_dat, aes(xintercept=mean, color=group), size = 1.5,
            # linetype="dashed")+
    #geom_vline(data=sum_dat, aes(xintercept=median, color=group), size = 1.5,
             #linetype="dashed") +
  geom_vline(xintercept = c(end_median, start_median), size = 1.8,
             linetype="dashed", color = c("royalblue3","red3")) +
  annotate(geom="text", vjust = 1.7, size = 5, x = c(35), y = c(14.5, 17), label = c("Current Age Median", "Starting Age Median")) +
   geom_segment(aes(x = 32, y = 15, xend = 38, yend = 15), linetype="dashed", size = 1.5, color = "red3")+
   geom_segment(aes(x = 32, y = 12.5, xend = 38, yend = 12.5), linetype="dashed", size = 1.5, color = "royalblue3")+
  labs(title = "Age of Finding Alex G and Current Age", subtitle = "Overlapping Histogram", y = "# of Individuals", x = "Age", legend = "") +
  scale_fill_discrete(name = "",labels=c("Starting Listening Age", "Current Age")) +
  theme_gray(base_size = 17) + theme(legend.position="top")
ggsave("start_age_current.png", width = 9, height = 7)

```

Year first head
```{r}
##Second histogram
fact_order <- as.character(sort(unique(dat$year_learned)))


dat_2 <- (dat %>% select(year_learned))

ggplot(dat_2, aes(x=year_learned)) +
  geom_histogram(color = "black",  fill = "grey", binwidth = 1)+
    scale_x_continuous(breaks=seq(2009,2020,2)) +
  
  geom_vline(xintercept = race, linetype="dotted", 
                color = "deeppink1", size=1.5) +
   geom_vline(xintercept = winner, 
                color = "yellow3", size=1.5, linetype ="dotted") + 
  geom_vline(xintercept = Rules_Trick, 
                color = "deepskyblue1", size= 1.5, linetype ="dotted") +
    geom_vline(xintercept = DSU, 
                color = "springgreen4", size= 1.5, linetype ="dotted") +
      geom_vline(xintercept = beach_music, 
                color = "royalblue4", size= 1.5, linetype ="dotted") +
        geom_vline(xintercept = rocket, 
                color = "red3", size= 1.5, linetype ="dotted")  +
          geom_vline(xintercept = HoS, 
                color = "darkorchid4", size= 1.5, linetype ="dotted") + 
  annotate(geom="text", angle = 90, vjust = 1.3, size = 5,  
           x=c(race, winner, Rules_Trick, DSU, beach_music, rocket, HoS), 
           y=c(10, 10, 10, 10, 10, 10, 10), 
           label=c("Race", "Winner", "Rules/Trick", "DSU", "Beach Music", "Rocket", "House of Sugar"),
              #color="red"
           color = c("deeppink", "yellow3", "deepskyblue1", "springgreen4", "royalblue4", "red3", "darkorchid4")
           ) +
          labs(title = "Histogram of when people first heard of Alex G", x = "Year First Heard", y = "# of Individuals") +
  theme_gray(base_size = 17)

ggsave("year_start_listening.png", width = 9, height = 7)

```


```{r}
dat_3 <- dat %>% select(difference)

ggplot(dat_3, aes(x=difference)) +
  geom_histogram(color = "black",  fill = "grey", binwidth = 1) + 
  scale_x_continuous(breaks=seq(min(dat_3$difference),max(dat_3$difference),1)) +
 # geom_vline(xintercept = mean(dat_3$difference)) +
  labs(title = "How Many Years Have We Been Listening?", x ="Length of Time in Years", y = "# of Indivduals") +
  theme_gray(base_size = 17)
  
ggsave("how_long_listening.png", width = 9, height = 7)

```


Cumulative distribution plot
```{r}

ggplot(dat, aes(x=year_learned)) + stat_ecdf() + scale_x_continuous(breaks=seq(2009,2020,2))+
  scale_y_continuous(labels = percent) +
  geom_vline(xintercept = race, linetype="dotted", 
                color = "deeppink1", size=1.5) +
   geom_vline(xintercept = winner, 
                color = "yellow3", size=1.5, linetype ="dotted") + 
  geom_vline(xintercept = Rules_Trick, 
                color = "deepskyblue1", size= 1.5, linetype ="dotted") +
    geom_vline(xintercept = DSU, 
                color = "springgreen4", size= 1.5, linetype ="dotted") +
      geom_vline(xintercept = beach_music, 
                color = "royalblue4", size= 1.5, linetype ="dotted") +
        geom_vline(xintercept = rocket, 
                color = "red3", size= 1.5, linetype ="dotted")  +
          geom_vline(xintercept = HoS, 
                color = "darkorchid4", size= 1.5, linetype ="dotted") + 
  annotate(geom="text", angle = 90, vjust = 1.3, size = 5,  
           x=c(race, winner, Rules_Trick, DSU, beach_music, rocket, HoS), 
           y=c(.10, .20, .30, .50, .80, .60, .75), 
           label=c("Race", "Winner", "Rules/Trick", "DSU", "Beach Music", "Rocket", "House of Sugar"),
              #color="red"
           color = c("deeppink", "yellow3", "deepskyblue1", "springgreen4", "royalblue4", "red3", "darkorchid4")
           ) +
          labs(title = "How has Alex G's Fanbase Grown?",subtitle = "Cummulative Distribution Plot of Alex G Fanbase Growth", x ="Year", y = "Percent of Current Fanbase") +
  theme_gray(base_size = 17)


ggsave("alex_g_fanbase_growth.png", width = 9, height = 7)


136/2774

```

