---
title: "spotifyr"
author: "Tim Nieuwenhuis"
date: "9/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spotifyr)
library(tidyverse)
library(knitr)

```


Set up API
```{r cars}
spt_cred <- read.csv("inputs/spotifyr_dat.csv")

Sys.setenv(SPOTIFY_CLIENT_ID = spot_cred$client_id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = spot_cred$shhh)
access_token <- get_spotify_access_token()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
library(spotifyr)
alex_g <- get_artist_audio_features('alex g')
#Remove duplicate tracks
alex_g <- alex_g %>% select(-album_id, -track_id, -analysis_url, - available_markets,
                                   -track_href, -track_preview_url, -track_uri, -external_urls.spotify,
                                   -album_images) %>% distinct()

alex_g %>% 
  count(key_mode, sort = TRUE) %>%
  head(10)
```
Valence Alex G
```{r}
ggplot(alex_g, aes(x = valence, fill = album_name)) +
  geom_density() +
  facet_grid(album_name~.)

ggplot(alex_g, aes(x = track_number, y= valence, fill = album_name)) +
  geom_bar(stat = "identity") +
  facet_grid(album_name~.) +
  scale_x_continuous(breaks = 1:16)

 alex_g %>%
  arrange(valence) %>%
  select(track_name, valence) %>%
  head(10) %>% unique()
 
  alex_g %>%
  arrange(desc(danceability)) %>%
  select(track_name, danceability) %>%
  head(10) %>% unique()
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
